#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbusImport.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Mokopane_New")]
	public partial class EbusDataContext : System.Data.Linq.DataContext
	{
		
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertModule(Module instance);
    partial void UpdateModule(Module instance);
    partial void DeleteModule(Module instance);
    partial void InsertDuty(Duty instance);
    partial void UpdateDuty(Duty instance);
    partial void DeleteDuty(Duty instance);
    partial void InsertJourney(Journey instance);
    partial void UpdateJourney(Journey instance);
    partial void DeleteJourney(Journey instance);
    partial void InsertStage(Stage instance);
    partial void UpdateStage(Stage instance);
    partial void DeleteStage(Stage instance);
    partial void InsertTran(Tran instance);
    partial void UpdateTran(Tran instance);
    partial void DeleteTran(Tran instance);
    #endregion
		
        //public EbusDataContext() : 
        //        base(global::EbusImport.Properties.Settings.Default.Mokopane_NewConnectionString, mappingSource)
        //{
        //    OnCreated();
        //}
		
		public EbusDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EbusDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EbusDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EbusDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Module> Modules
		{
			get
			{
				return this.GetTable<Module>();
			}
		}
		
		public System.Data.Linq.Table<Duty> Duties
		{
			get
			{
				return this.GetTable<Duty>();
			}
		}
		
		public System.Data.Linq.Table<Journey> Journeys
		{
			get
			{
				return this.GetTable<Journey>();
			}
		}
		
		public System.Data.Linq.Table<Stage> Stages
		{
			get
			{
				return this.GetTable<Stage>();
			}
		}
		
		public System.Data.Linq.Table<Tran> Trans
		{
			get
			{
				return this.GetTable<Tran>();
			}
		}
		
		public System.Data.Linq.Table<Waybill> Waybills
		{
			get
			{
				return this.GetTable<Waybill>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertWaybil")]
		public int InsertWaybil([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModuleID", DbType="Int")] System.Nullable<int> moduleID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dat_Start, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dat_End, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> int4_Operator, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string str8_BusID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string str6_EtmID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> int4_EtmGrandTotal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> int4_Revenue)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), moduleID, dat_Start, dat_End, int4_Operator, str8_BusID, str6_EtmID, int4_EtmGrandTotal, int4_Revenue);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Module")]
	public partial class Module : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Module;
		
		private string _str_LocationCode;
		
		private System.Nullable<int> _int4_ModuleID;
		
		private System.Nullable<int> _int4_SignOnID;
		
		private System.Nullable<int> _int4_OnReaderID;
		
		private System.Nullable<System.DateTime> _dat_SignOnDate;
		
		private System.Nullable<System.DateTime> _dat_SignOnTime;
		
		private System.Nullable<int> _int4_OffReaderID;
		
		private System.Nullable<System.DateTime> _dat_SignOffDate;
		
		private System.Nullable<System.DateTime> _dat_SignOffTime;
		
		private System.Nullable<System.DateTime> _dat_TrafficDate;
		
		private System.Nullable<System.DateTime> _dat_ModuleOutDate;
		
		private System.Nullable<System.DateTime> _dat_ModuleOutTime;
		
		private System.Nullable<int> _int4_HdrModuleRevenue;
		
		private System.Nullable<int> _int4_HdrModuleTickets;
		
		private System.Nullable<int> _int4_HdrModulePasses;
		
		private System.Nullable<int> _int4_ModuleRevenue;
		
		private System.Nullable<int> _int4_ModuleTickets;
		
		private System.Nullable<int> _int4_ModulePasses;
		
		private System.Nullable<int> _int4_ModuleNonRevenue;
		
		private System.Nullable<int> _int4_ModuleTransfer;
		
		private System.Nullable<System.DateTime> _dat_ImportStamp;
		
		private System.Nullable<System.DateTime> _dat_RecordMod;
		
		private System.Nullable<int> _int4_ImportModuleKey;
		
		private System.Nullable<int> _id_BatchNo;
		
		private System.Nullable<byte> _byt_IeType;
		
		private System.Nullable<int> _byt_ModuleType;
		
		private string _oFilename;
		
		private System.Nullable<System.DateTime> _oFileDateTime;
		
		private string _nFilename;
		
		private EntitySet<Duty> _Duties;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ModuleChanging(int value);
    partial void Onid_ModuleChanged();
    partial void Onstr_LocationCodeChanging(string value);
    partial void Onstr_LocationCodeChanged();
    partial void Onint4_ModuleIDChanging(System.Nullable<int> value);
    partial void Onint4_ModuleIDChanged();
    partial void Onint4_SignOnIDChanging(System.Nullable<int> value);
    partial void Onint4_SignOnIDChanged();
    partial void Onint4_OnReaderIDChanging(System.Nullable<int> value);
    partial void Onint4_OnReaderIDChanged();
    partial void Ondat_SignOnDateChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_SignOnDateChanged();
    partial void Ondat_SignOnTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_SignOnTimeChanged();
    partial void Onint4_OffReaderIDChanging(System.Nullable<int> value);
    partial void Onint4_OffReaderIDChanged();
    partial void Ondat_SignOffDateChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_SignOffDateChanged();
    partial void Ondat_SignOffTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_SignOffTimeChanged();
    partial void Ondat_TrafficDateChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_TrafficDateChanged();
    partial void Ondat_ModuleOutDateChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_ModuleOutDateChanged();
    partial void Ondat_ModuleOutTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_ModuleOutTimeChanged();
    partial void Onint4_HdrModuleRevenueChanging(System.Nullable<int> value);
    partial void Onint4_HdrModuleRevenueChanged();
    partial void Onint4_HdrModuleTicketsChanging(System.Nullable<int> value);
    partial void Onint4_HdrModuleTicketsChanged();
    partial void Onint4_HdrModulePassesChanging(System.Nullable<int> value);
    partial void Onint4_HdrModulePassesChanged();
    partial void Onint4_ModuleRevenueChanging(System.Nullable<int> value);
    partial void Onint4_ModuleRevenueChanged();
    partial void Onint4_ModuleTicketsChanging(System.Nullable<int> value);
    partial void Onint4_ModuleTicketsChanged();
    partial void Onint4_ModulePassesChanging(System.Nullable<int> value);
    partial void Onint4_ModulePassesChanged();
    partial void Onint4_ModuleNonRevenueChanging(System.Nullable<int> value);
    partial void Onint4_ModuleNonRevenueChanged();
    partial void Onint4_ModuleTransferChanging(System.Nullable<int> value);
    partial void Onint4_ModuleTransferChanged();
    partial void Ondat_ImportStampChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_ImportStampChanged();
    partial void Ondat_RecordModChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_RecordModChanged();
    partial void Onint4_ImportModuleKeyChanging(System.Nullable<int> value);
    partial void Onint4_ImportModuleKeyChanged();
    partial void Onid_BatchNoChanging(System.Nullable<int> value);
    partial void Onid_BatchNoChanged();
    partial void Onbyt_IeTypeChanging(System.Nullable<byte> value);
    partial void Onbyt_IeTypeChanged();
    partial void Onbyt_ModuleTypeChanging(System.Nullable<int> value);
    partial void Onbyt_ModuleTypeChanged();
    partial void OnoFilenameChanging(string value);
    partial void OnoFilenameChanged();
    partial void OnoFileDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnoFileDateTimeChanged();
    partial void OnnFilenameChanging(string value);
    partial void OnnFilenameChanged();
    #endregion
		
		public Module()
		{
			this._Duties = new EntitySet<Duty>(new Action<Duty>(this.attach_Duties), new Action<Duty>(this.detach_Duties));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Module", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_Module
		{
			get
			{
				return this._id_Module;
			}
			set
			{
				if ((this._id_Module != value))
				{
					this.Onid_ModuleChanging(value);
					this.SendPropertyChanging();
					this._id_Module = value;
					this.SendPropertyChanged("id_Module");
					this.Onid_ModuleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_str_LocationCode", DbType="Char(2)")]
		public string str_LocationCode
		{
			get
			{
				return this._str_LocationCode;
			}
			set
			{
				if ((this._str_LocationCode != value))
				{
					this.Onstr_LocationCodeChanging(value);
					this.SendPropertyChanging();
					this._str_LocationCode = value;
					this.SendPropertyChanged("str_LocationCode");
					this.Onstr_LocationCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_ModuleID", DbType="Int")]
		public System.Nullable<int> int4_ModuleID
		{
			get
			{
				return this._int4_ModuleID;
			}
			set
			{
				if ((this._int4_ModuleID != value))
				{
					this.Onint4_ModuleIDChanging(value);
					this.SendPropertyChanging();
					this._int4_ModuleID = value;
					this.SendPropertyChanged("int4_ModuleID");
					this.Onint4_ModuleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_SignOnID", DbType="Int")]
		public System.Nullable<int> int4_SignOnID
		{
			get
			{
				return this._int4_SignOnID;
			}
			set
			{
				if ((this._int4_SignOnID != value))
				{
					this.Onint4_SignOnIDChanging(value);
					this.SendPropertyChanging();
					this._int4_SignOnID = value;
					this.SendPropertyChanged("int4_SignOnID");
					this.Onint4_SignOnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_OnReaderID", DbType="Int")]
		public System.Nullable<int> int4_OnReaderID
		{
			get
			{
				return this._int4_OnReaderID;
			}
			set
			{
				if ((this._int4_OnReaderID != value))
				{
					this.Onint4_OnReaderIDChanging(value);
					this.SendPropertyChanging();
					this._int4_OnReaderID = value;
					this.SendPropertyChanged("int4_OnReaderID");
					this.Onint4_OnReaderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_SignOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_SignOnDate
		{
			get
			{
				return this._dat_SignOnDate;
			}
			set
			{
				if ((this._dat_SignOnDate != value))
				{
					this.Ondat_SignOnDateChanging(value);
					this.SendPropertyChanging();
					this._dat_SignOnDate = value;
					this.SendPropertyChanged("dat_SignOnDate");
					this.Ondat_SignOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_SignOnTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_SignOnTime
		{
			get
			{
				return this._dat_SignOnTime;
			}
			set
			{
				if ((this._dat_SignOnTime != value))
				{
					this.Ondat_SignOnTimeChanging(value);
					this.SendPropertyChanging();
					this._dat_SignOnTime = value;
					this.SendPropertyChanged("dat_SignOnTime");
					this.Ondat_SignOnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_OffReaderID", DbType="Int")]
		public System.Nullable<int> int4_OffReaderID
		{
			get
			{
				return this._int4_OffReaderID;
			}
			set
			{
				if ((this._int4_OffReaderID != value))
				{
					this.Onint4_OffReaderIDChanging(value);
					this.SendPropertyChanging();
					this._int4_OffReaderID = value;
					this.SendPropertyChanged("int4_OffReaderID");
					this.Onint4_OffReaderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_SignOffDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_SignOffDate
		{
			get
			{
				return this._dat_SignOffDate;
			}
			set
			{
				if ((this._dat_SignOffDate != value))
				{
					this.Ondat_SignOffDateChanging(value);
					this.SendPropertyChanging();
					this._dat_SignOffDate = value;
					this.SendPropertyChanged("dat_SignOffDate");
					this.Ondat_SignOffDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_SignOffTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_SignOffTime
		{
			get
			{
				return this._dat_SignOffTime;
			}
			set
			{
				if ((this._dat_SignOffTime != value))
				{
					this.Ondat_SignOffTimeChanging(value);
					this.SendPropertyChanging();
					this._dat_SignOffTime = value;
					this.SendPropertyChanged("dat_SignOffTime");
					this.Ondat_SignOffTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_TrafficDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_TrafficDate
		{
			get
			{
				return this._dat_TrafficDate;
			}
			set
			{
				if ((this._dat_TrafficDate != value))
				{
					this.Ondat_TrafficDateChanging(value);
					this.SendPropertyChanging();
					this._dat_TrafficDate = value;
					this.SendPropertyChanged("dat_TrafficDate");
					this.Ondat_TrafficDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_ModuleOutDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_ModuleOutDate
		{
			get
			{
				return this._dat_ModuleOutDate;
			}
			set
			{
				if ((this._dat_ModuleOutDate != value))
				{
					this.Ondat_ModuleOutDateChanging(value);
					this.SendPropertyChanging();
					this._dat_ModuleOutDate = value;
					this.SendPropertyChanged("dat_ModuleOutDate");
					this.Ondat_ModuleOutDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_ModuleOutTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_ModuleOutTime
		{
			get
			{
				return this._dat_ModuleOutTime;
			}
			set
			{
				if ((this._dat_ModuleOutTime != value))
				{
					this.Ondat_ModuleOutTimeChanging(value);
					this.SendPropertyChanging();
					this._dat_ModuleOutTime = value;
					this.SendPropertyChanged("dat_ModuleOutTime");
					this.Ondat_ModuleOutTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_HdrModuleRevenue", DbType="Int")]
		public System.Nullable<int> int4_HdrModuleRevenue
		{
			get
			{
				return this._int4_HdrModuleRevenue;
			}
			set
			{
				if ((this._int4_HdrModuleRevenue != value))
				{
					this.Onint4_HdrModuleRevenueChanging(value);
					this.SendPropertyChanging();
					this._int4_HdrModuleRevenue = value;
					this.SendPropertyChanged("int4_HdrModuleRevenue");
					this.Onint4_HdrModuleRevenueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_HdrModuleTickets", DbType="Int")]
		public System.Nullable<int> int4_HdrModuleTickets
		{
			get
			{
				return this._int4_HdrModuleTickets;
			}
			set
			{
				if ((this._int4_HdrModuleTickets != value))
				{
					this.Onint4_HdrModuleTicketsChanging(value);
					this.SendPropertyChanging();
					this._int4_HdrModuleTickets = value;
					this.SendPropertyChanged("int4_HdrModuleTickets");
					this.Onint4_HdrModuleTicketsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_HdrModulePasses", DbType="Int")]
		public System.Nullable<int> int4_HdrModulePasses
		{
			get
			{
				return this._int4_HdrModulePasses;
			}
			set
			{
				if ((this._int4_HdrModulePasses != value))
				{
					this.Onint4_HdrModulePassesChanging(value);
					this.SendPropertyChanging();
					this._int4_HdrModulePasses = value;
					this.SendPropertyChanged("int4_HdrModulePasses");
					this.Onint4_HdrModulePassesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_ModuleRevenue", DbType="Int")]
		public System.Nullable<int> int4_ModuleRevenue
		{
			get
			{
				return this._int4_ModuleRevenue;
			}
			set
			{
				if ((this._int4_ModuleRevenue != value))
				{
					this.Onint4_ModuleRevenueChanging(value);
					this.SendPropertyChanging();
					this._int4_ModuleRevenue = value;
					this.SendPropertyChanged("int4_ModuleRevenue");
					this.Onint4_ModuleRevenueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_ModuleTickets", DbType="Int")]
		public System.Nullable<int> int4_ModuleTickets
		{
			get
			{
				return this._int4_ModuleTickets;
			}
			set
			{
				if ((this._int4_ModuleTickets != value))
				{
					this.Onint4_ModuleTicketsChanging(value);
					this.SendPropertyChanging();
					this._int4_ModuleTickets = value;
					this.SendPropertyChanged("int4_ModuleTickets");
					this.Onint4_ModuleTicketsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_ModulePasses", DbType="Int")]
		public System.Nullable<int> int4_ModulePasses
		{
			get
			{
				return this._int4_ModulePasses;
			}
			set
			{
				if ((this._int4_ModulePasses != value))
				{
					this.Onint4_ModulePassesChanging(value);
					this.SendPropertyChanging();
					this._int4_ModulePasses = value;
					this.SendPropertyChanged("int4_ModulePasses");
					this.Onint4_ModulePassesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_ModuleNonRevenue", DbType="Int")]
		public System.Nullable<int> int4_ModuleNonRevenue
		{
			get
			{
				return this._int4_ModuleNonRevenue;
			}
			set
			{
				if ((this._int4_ModuleNonRevenue != value))
				{
					this.Onint4_ModuleNonRevenueChanging(value);
					this.SendPropertyChanging();
					this._int4_ModuleNonRevenue = value;
					this.SendPropertyChanged("int4_ModuleNonRevenue");
					this.Onint4_ModuleNonRevenueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_ModuleTransfer", DbType="Int")]
		public System.Nullable<int> int4_ModuleTransfer
		{
			get
			{
				return this._int4_ModuleTransfer;
			}
			set
			{
				if ((this._int4_ModuleTransfer != value))
				{
					this.Onint4_ModuleTransferChanging(value);
					this.SendPropertyChanging();
					this._int4_ModuleTransfer = value;
					this.SendPropertyChanged("int4_ModuleTransfer");
					this.Onint4_ModuleTransferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_ImportStamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_ImportStamp
		{
			get
			{
				return this._dat_ImportStamp;
			}
			set
			{
				if ((this._dat_ImportStamp != value))
				{
					this.Ondat_ImportStampChanging(value);
					this.SendPropertyChanging();
					this._dat_ImportStamp = value;
					this.SendPropertyChanged("dat_ImportStamp");
					this.Ondat_ImportStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_RecordMod", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_RecordMod
		{
			get
			{
				return this._dat_RecordMod;
			}
			set
			{
				if ((this._dat_RecordMod != value))
				{
					this.Ondat_RecordModChanging(value);
					this.SendPropertyChanging();
					this._dat_RecordMod = value;
					this.SendPropertyChanged("dat_RecordMod");
					this.Ondat_RecordModChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_ImportModuleKey", DbType="Int")]
		public System.Nullable<int> int4_ImportModuleKey
		{
			get
			{
				return this._int4_ImportModuleKey;
			}
			set
			{
				if ((this._int4_ImportModuleKey != value))
				{
					this.Onint4_ImportModuleKeyChanging(value);
					this.SendPropertyChanging();
					this._int4_ImportModuleKey = value;
					this.SendPropertyChanged("int4_ImportModuleKey");
					this.Onint4_ImportModuleKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_BatchNo", DbType="Int")]
		public System.Nullable<int> id_BatchNo
		{
			get
			{
				return this._id_BatchNo;
			}
			set
			{
				if ((this._id_BatchNo != value))
				{
					this.Onid_BatchNoChanging(value);
					this.SendPropertyChanging();
					this._id_BatchNo = value;
					this.SendPropertyChanged("id_BatchNo");
					this.Onid_BatchNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_byt_IeType", DbType="TinyInt")]
		public System.Nullable<byte> byt_IeType
		{
			get
			{
				return this._byt_IeType;
			}
			set
			{
				if ((this._byt_IeType != value))
				{
					this.Onbyt_IeTypeChanging(value);
					this.SendPropertyChanging();
					this._byt_IeType = value;
					this.SendPropertyChanged("byt_IeType");
					this.Onbyt_IeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_byt_ModuleType", DbType="Int")]
		public System.Nullable<int> byt_ModuleType
		{
			get
			{
				return this._byt_ModuleType;
			}
			set
			{
				if ((this._byt_ModuleType != value))
				{
					this.Onbyt_ModuleTypeChanging(value);
					this.SendPropertyChanging();
					this._byt_ModuleType = value;
					this.SendPropertyChanged("byt_ModuleType");
					this.Onbyt_ModuleTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oFilename", DbType="VarChar(255)")]
		public string oFilename
		{
			get
			{
				return this._oFilename;
			}
			set
			{
				if ((this._oFilename != value))
				{
					this.OnoFilenameChanging(value);
					this.SendPropertyChanging();
					this._oFilename = value;
					this.SendPropertyChanged("oFilename");
					this.OnoFilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oFileDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> oFileDateTime
		{
			get
			{
				return this._oFileDateTime;
			}
			set
			{
				if ((this._oFileDateTime != value))
				{
					this.OnoFileDateTimeChanging(value);
					this.SendPropertyChanging();
					this._oFileDateTime = value;
					this.SendPropertyChanged("oFileDateTime");
					this.OnoFileDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nFilename", DbType="VarChar(255)")]
		public string nFilename
		{
			get
			{
				return this._nFilename;
			}
			set
			{
				if ((this._nFilename != value))
				{
					this.OnnFilenameChanging(value);
					this.SendPropertyChanging();
					this._nFilename = value;
					this.SendPropertyChanged("nFilename");
					this.OnnFilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Module_Duty", Storage="_Duties", ThisKey="id_Module", OtherKey="id_Module")]
		public EntitySet<Duty> Duties
		{
			get
			{
				return this._Duties;
			}
			set
			{
				this._Duties.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Duties(Duty entity)
		{
			this.SendPropertyChanging();
			entity.Module = this;
		}
		
		private void detach_Duties(Duty entity)
		{
			this.SendPropertyChanging();
			entity.Module = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Duty")]
	public partial class Duty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Duty;
		
		private int _id_Module;
		
		private int _int4_DutyID;
		
		private System.Nullable<int> _int4_OperatorID;
		
		private string _str_ETMID;
		
		private System.Nullable<int> _int4_GTValue;
		
		private System.Nullable<int> _int4_NextTicketNumber;
		
		private System.Nullable<int> _int4_DutySeqNum;
		
		private System.Nullable<System.DateTime> _dat_DutyStartDate;
		
		private System.Nullable<System.DateTime> _dat_DutyStartTime;
		
		private System.Nullable<System.DateTime> _dat_DutyStopDate;
		
		private System.Nullable<System.DateTime> _dat_DutyStopTime;
		
		private System.Nullable<System.DateTime> _dat_TrafficDate;
		
		private string _str_BusID;
		
		private System.Nullable<int> _int4_DutyRevenue;
		
		private System.Nullable<int> _int4_DutyTickets;
		
		private System.Nullable<int> _int4_DutyPasses;
		
		private System.Nullable<int> _int4_DutyNonRevenue;
		
		private System.Nullable<int> _int4_DutyTransfer;
		
		private string _str_FirstRouteID;
		
		private System.Nullable<short> _int2_FirstJourneyID;
		
		private System.Nullable<System.DateTime> _dat_RecordMod;
		
		private System.Nullable<int> _id_BatchNo;
		
		private System.Nullable<byte> _byt_IeType;
		
		private string _str_EpromVersion;
		
		private string _str_OperatorVersion;
		
		private string _str_SpecialVersion;
		
		private System.Nullable<int> _int4_DutyAnnulCash;
		
		private System.Nullable<int> _int4_DutyAnnulCount;
		
		private EntitySet<Journey> _Journeys;
		
		private EntityRef<Module> _Module;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_DutyChanging(int value);
    partial void Onid_DutyChanged();
    partial void Onid_ModuleChanging(int value);
    partial void Onid_ModuleChanged();
    partial void Onint4_DutyIDChanging(int value);
    partial void Onint4_DutyIDChanged();
    partial void Onint4_OperatorIDChanging(System.Nullable<int> value);
    partial void Onint4_OperatorIDChanged();
    partial void Onstr_ETMIDChanging(string value);
    partial void Onstr_ETMIDChanged();
    partial void Onint4_GTValueChanging(System.Nullable<int> value);
    partial void Onint4_GTValueChanged();
    partial void Onint4_NextTicketNumberChanging(System.Nullable<int> value);
    partial void Onint4_NextTicketNumberChanged();
    partial void Onint4_DutySeqNumChanging(System.Nullable<int> value);
    partial void Onint4_DutySeqNumChanged();
    partial void Ondat_DutyStartDateChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_DutyStartDateChanged();
    partial void Ondat_DutyStartTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_DutyStartTimeChanged();
    partial void Ondat_DutyStopDateChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_DutyStopDateChanged();
    partial void Ondat_DutyStopTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_DutyStopTimeChanged();
    partial void Ondat_TrafficDateChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_TrafficDateChanged();
    partial void Onstr_BusIDChanging(string value);
    partial void Onstr_BusIDChanged();
    partial void Onint4_DutyRevenueChanging(System.Nullable<int> value);
    partial void Onint4_DutyRevenueChanged();
    partial void Onint4_DutyTicketsChanging(System.Nullable<int> value);
    partial void Onint4_DutyTicketsChanged();
    partial void Onint4_DutyPassesChanging(System.Nullable<int> value);
    partial void Onint4_DutyPassesChanged();
    partial void Onint4_DutyNonRevenueChanging(System.Nullable<int> value);
    partial void Onint4_DutyNonRevenueChanged();
    partial void Onint4_DutyTransferChanging(System.Nullable<int> value);
    partial void Onint4_DutyTransferChanged();
    partial void Onstr_FirstRouteIDChanging(string value);
    partial void Onstr_FirstRouteIDChanged();
    partial void Onint2_FirstJourneyIDChanging(System.Nullable<short> value);
    partial void Onint2_FirstJourneyIDChanged();
    partial void Ondat_RecordModChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_RecordModChanged();
    partial void Onid_BatchNoChanging(System.Nullable<int> value);
    partial void Onid_BatchNoChanged();
    partial void Onbyt_IeTypeChanging(System.Nullable<byte> value);
    partial void Onbyt_IeTypeChanged();
    partial void Onstr_EpromVersionChanging(string value);
    partial void Onstr_EpromVersionChanged();
    partial void Onstr_OperatorVersionChanging(string value);
    partial void Onstr_OperatorVersionChanged();
    partial void Onstr_SpecialVersionChanging(string value);
    partial void Onstr_SpecialVersionChanged();
    partial void Onint4_DutyAnnulCashChanging(System.Nullable<int> value);
    partial void Onint4_DutyAnnulCashChanged();
    partial void Onint4_DutyAnnulCountChanging(System.Nullable<int> value);
    partial void Onint4_DutyAnnulCountChanged();
    #endregion
		
		public Duty()
		{
			this._Journeys = new EntitySet<Journey>(new Action<Journey>(this.attach_Journeys), new Action<Journey>(this.detach_Journeys));
			this._Module = default(EntityRef<Module>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Duty", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_Duty
		{
			get
			{
				return this._id_Duty;
			}
			set
			{
				if ((this._id_Duty != value))
				{
					this.Onid_DutyChanging(value);
					this.SendPropertyChanging();
					this._id_Duty = value;
					this.SendPropertyChanged("id_Duty");
					this.Onid_DutyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Module", DbType="Int NOT NULL")]
		public int id_Module
		{
			get
			{
				return this._id_Module;
			}
			set
			{
				if ((this._id_Module != value))
				{
					if (this._Module.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_ModuleChanging(value);
					this.SendPropertyChanging();
					this._id_Module = value;
					this.SendPropertyChanged("id_Module");
					this.Onid_ModuleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_DutyID", DbType="Int NOT NULL")]
		public int int4_DutyID
		{
			get
			{
				return this._int4_DutyID;
			}
			set
			{
				if ((this._int4_DutyID != value))
				{
					this.Onint4_DutyIDChanging(value);
					this.SendPropertyChanging();
					this._int4_DutyID = value;
					this.SendPropertyChanged("int4_DutyID");
					this.Onint4_DutyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_OperatorID", DbType="Int")]
		public System.Nullable<int> int4_OperatorID
		{
			get
			{
				return this._int4_OperatorID;
			}
			set
			{
				if ((this._int4_OperatorID != value))
				{
					this.Onint4_OperatorIDChanging(value);
					this.SendPropertyChanging();
					this._int4_OperatorID = value;
					this.SendPropertyChanged("int4_OperatorID");
					this.Onint4_OperatorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_str_ETMID", DbType="Char(6)")]
		public string str_ETMID
		{
			get
			{
				return this._str_ETMID;
			}
			set
			{
				if ((this._str_ETMID != value))
				{
					this.Onstr_ETMIDChanging(value);
					this.SendPropertyChanging();
					this._str_ETMID = value;
					this.SendPropertyChanged("str_ETMID");
					this.Onstr_ETMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_GTValue", DbType="Int")]
		public System.Nullable<int> int4_GTValue
		{
			get
			{
				return this._int4_GTValue;
			}
			set
			{
				if ((this._int4_GTValue != value))
				{
					this.Onint4_GTValueChanging(value);
					this.SendPropertyChanging();
					this._int4_GTValue = value;
					this.SendPropertyChanged("int4_GTValue");
					this.Onint4_GTValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_NextTicketNumber", DbType="Int")]
		public System.Nullable<int> int4_NextTicketNumber
		{
			get
			{
				return this._int4_NextTicketNumber;
			}
			set
			{
				if ((this._int4_NextTicketNumber != value))
				{
					this.Onint4_NextTicketNumberChanging(value);
					this.SendPropertyChanging();
					this._int4_NextTicketNumber = value;
					this.SendPropertyChanged("int4_NextTicketNumber");
					this.Onint4_NextTicketNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_DutySeqNum", DbType="Int")]
		public System.Nullable<int> int4_DutySeqNum
		{
			get
			{
				return this._int4_DutySeqNum;
			}
			set
			{
				if ((this._int4_DutySeqNum != value))
				{
					this.Onint4_DutySeqNumChanging(value);
					this.SendPropertyChanging();
					this._int4_DutySeqNum = value;
					this.SendPropertyChanged("int4_DutySeqNum");
					this.Onint4_DutySeqNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_DutyStartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_DutyStartDate
		{
			get
			{
				return this._dat_DutyStartDate;
			}
			set
			{
				if ((this._dat_DutyStartDate != value))
				{
					this.Ondat_DutyStartDateChanging(value);
					this.SendPropertyChanging();
					this._dat_DutyStartDate = value;
					this.SendPropertyChanged("dat_DutyStartDate");
					this.Ondat_DutyStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_DutyStartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_DutyStartTime
		{
			get
			{
				return this._dat_DutyStartTime;
			}
			set
			{
				if ((this._dat_DutyStartTime != value))
				{
					this.Ondat_DutyStartTimeChanging(value);
					this.SendPropertyChanging();
					this._dat_DutyStartTime = value;
					this.SendPropertyChanged("dat_DutyStartTime");
					this.Ondat_DutyStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_DutyStopDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_DutyStopDate
		{
			get
			{
				return this._dat_DutyStopDate;
			}
			set
			{
				if ((this._dat_DutyStopDate != value))
				{
					this.Ondat_DutyStopDateChanging(value);
					this.SendPropertyChanging();
					this._dat_DutyStopDate = value;
					this.SendPropertyChanged("dat_DutyStopDate");
					this.Ondat_DutyStopDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_DutyStopTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_DutyStopTime
		{
			get
			{
				return this._dat_DutyStopTime;
			}
			set
			{
				if ((this._dat_DutyStopTime != value))
				{
					this.Ondat_DutyStopTimeChanging(value);
					this.SendPropertyChanging();
					this._dat_DutyStopTime = value;
					this.SendPropertyChanged("dat_DutyStopTime");
					this.Ondat_DutyStopTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_TrafficDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_TrafficDate
		{
			get
			{
				return this._dat_TrafficDate;
			}
			set
			{
				if ((this._dat_TrafficDate != value))
				{
					this.Ondat_TrafficDateChanging(value);
					this.SendPropertyChanging();
					this._dat_TrafficDate = value;
					this.SendPropertyChanged("dat_TrafficDate");
					this.Ondat_TrafficDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_str_BusID", DbType="Char(8)")]
		public string str_BusID
		{
			get
			{
				return this._str_BusID;
			}
			set
			{
				if ((this._str_BusID != value))
				{
					this.Onstr_BusIDChanging(value);
					this.SendPropertyChanging();
					this._str_BusID = value;
					this.SendPropertyChanged("str_BusID");
					this.Onstr_BusIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_DutyRevenue", DbType="Int")]
		public System.Nullable<int> int4_DutyRevenue
		{
			get
			{
				return this._int4_DutyRevenue;
			}
			set
			{
				if ((this._int4_DutyRevenue != value))
				{
					this.Onint4_DutyRevenueChanging(value);
					this.SendPropertyChanging();
					this._int4_DutyRevenue = value;
					this.SendPropertyChanged("int4_DutyRevenue");
					this.Onint4_DutyRevenueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_DutyTickets", DbType="Int")]
		public System.Nullable<int> int4_DutyTickets
		{
			get
			{
				return this._int4_DutyTickets;
			}
			set
			{
				if ((this._int4_DutyTickets != value))
				{
					this.Onint4_DutyTicketsChanging(value);
					this.SendPropertyChanging();
					this._int4_DutyTickets = value;
					this.SendPropertyChanged("int4_DutyTickets");
					this.Onint4_DutyTicketsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_DutyPasses", DbType="Int")]
		public System.Nullable<int> int4_DutyPasses
		{
			get
			{
				return this._int4_DutyPasses;
			}
			set
			{
				if ((this._int4_DutyPasses != value))
				{
					this.Onint4_DutyPassesChanging(value);
					this.SendPropertyChanging();
					this._int4_DutyPasses = value;
					this.SendPropertyChanged("int4_DutyPasses");
					this.Onint4_DutyPassesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_DutyNonRevenue", DbType="Int")]
		public System.Nullable<int> int4_DutyNonRevenue
		{
			get
			{
				return this._int4_DutyNonRevenue;
			}
			set
			{
				if ((this._int4_DutyNonRevenue != value))
				{
					this.Onint4_DutyNonRevenueChanging(value);
					this.SendPropertyChanging();
					this._int4_DutyNonRevenue = value;
					this.SendPropertyChanged("int4_DutyNonRevenue");
					this.Onint4_DutyNonRevenueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_DutyTransfer", DbType="Int")]
		public System.Nullable<int> int4_DutyTransfer
		{
			get
			{
				return this._int4_DutyTransfer;
			}
			set
			{
				if ((this._int4_DutyTransfer != value))
				{
					this.Onint4_DutyTransferChanging(value);
					this.SendPropertyChanging();
					this._int4_DutyTransfer = value;
					this.SendPropertyChanged("int4_DutyTransfer");
					this.Onint4_DutyTransferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_str_FirstRouteID", DbType="Char(4)")]
		public string str_FirstRouteID
		{
			get
			{
				return this._str_FirstRouteID;
			}
			set
			{
				if ((this._str_FirstRouteID != value))
				{
					this.Onstr_FirstRouteIDChanging(value);
					this.SendPropertyChanging();
					this._str_FirstRouteID = value;
					this.SendPropertyChanged("str_FirstRouteID");
					this.Onstr_FirstRouteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int2_FirstJourneyID", DbType="SmallInt")]
		public System.Nullable<short> int2_FirstJourneyID
		{
			get
			{
				return this._int2_FirstJourneyID;
			}
			set
			{
				if ((this._int2_FirstJourneyID != value))
				{
					this.Onint2_FirstJourneyIDChanging(value);
					this.SendPropertyChanging();
					this._int2_FirstJourneyID = value;
					this.SendPropertyChanged("int2_FirstJourneyID");
					this.Onint2_FirstJourneyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_RecordMod", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_RecordMod
		{
			get
			{
				return this._dat_RecordMod;
			}
			set
			{
				if ((this._dat_RecordMod != value))
				{
					this.Ondat_RecordModChanging(value);
					this.SendPropertyChanging();
					this._dat_RecordMod = value;
					this.SendPropertyChanged("dat_RecordMod");
					this.Ondat_RecordModChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_BatchNo", DbType="Int")]
		public System.Nullable<int> id_BatchNo
		{
			get
			{
				return this._id_BatchNo;
			}
			set
			{
				if ((this._id_BatchNo != value))
				{
					this.Onid_BatchNoChanging(value);
					this.SendPropertyChanging();
					this._id_BatchNo = value;
					this.SendPropertyChanged("id_BatchNo");
					this.Onid_BatchNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_byt_IeType", DbType="TinyInt")]
		public System.Nullable<byte> byt_IeType
		{
			get
			{
				return this._byt_IeType;
			}
			set
			{
				if ((this._byt_IeType != value))
				{
					this.Onbyt_IeTypeChanging(value);
					this.SendPropertyChanging();
					this._byt_IeType = value;
					this.SendPropertyChanged("byt_IeType");
					this.Onbyt_IeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_str_EpromVersion", DbType="VarChar(8)")]
		public string str_EpromVersion
		{
			get
			{
				return this._str_EpromVersion;
			}
			set
			{
				if ((this._str_EpromVersion != value))
				{
					this.Onstr_EpromVersionChanging(value);
					this.SendPropertyChanging();
					this._str_EpromVersion = value;
					this.SendPropertyChanged("str_EpromVersion");
					this.Onstr_EpromVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_str_OperatorVersion", DbType="VarChar(8)")]
		public string str_OperatorVersion
		{
			get
			{
				return this._str_OperatorVersion;
			}
			set
			{
				if ((this._str_OperatorVersion != value))
				{
					this.Onstr_OperatorVersionChanging(value);
					this.SendPropertyChanging();
					this._str_OperatorVersion = value;
					this.SendPropertyChanged("str_OperatorVersion");
					this.Onstr_OperatorVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_str_SpecialVersion", DbType="VarChar(8)")]
		public string str_SpecialVersion
		{
			get
			{
				return this._str_SpecialVersion;
			}
			set
			{
				if ((this._str_SpecialVersion != value))
				{
					this.Onstr_SpecialVersionChanging(value);
					this.SendPropertyChanging();
					this._str_SpecialVersion = value;
					this.SendPropertyChanged("str_SpecialVersion");
					this.Onstr_SpecialVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_DutyAnnulCash", DbType="Int")]
		public System.Nullable<int> int4_DutyAnnulCash
		{
			get
			{
				return this._int4_DutyAnnulCash;
			}
			set
			{
				if ((this._int4_DutyAnnulCash != value))
				{
					this.Onint4_DutyAnnulCashChanging(value);
					this.SendPropertyChanging();
					this._int4_DutyAnnulCash = value;
					this.SendPropertyChanged("int4_DutyAnnulCash");
					this.Onint4_DutyAnnulCashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_DutyAnnulCount", DbType="Int")]
		public System.Nullable<int> int4_DutyAnnulCount
		{
			get
			{
				return this._int4_DutyAnnulCount;
			}
			set
			{
				if ((this._int4_DutyAnnulCount != value))
				{
					this.Onint4_DutyAnnulCountChanging(value);
					this.SendPropertyChanging();
					this._int4_DutyAnnulCount = value;
					this.SendPropertyChanged("int4_DutyAnnulCount");
					this.Onint4_DutyAnnulCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Duty_Journey", Storage="_Journeys", ThisKey="id_Duty", OtherKey="id_Duty")]
		public EntitySet<Journey> Journeys
		{
			get
			{
				return this._Journeys;
			}
			set
			{
				this._Journeys.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Module_Duty", Storage="_Module", ThisKey="id_Module", OtherKey="id_Module", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Module Module
		{
			get
			{
				return this._Module.Entity;
			}
			set
			{
				Module previousValue = this._Module.Entity;
				if (((previousValue != value) 
							|| (this._Module.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Module.Entity = null;
						previousValue.Duties.Remove(this);
					}
					this._Module.Entity = value;
					if ((value != null))
					{
						value.Duties.Add(this);
						this._id_Module = value.id_Module;
					}
					else
					{
						this._id_Module = default(int);
					}
					this.SendPropertyChanged("Module");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Journeys(Journey entity)
		{
			this.SendPropertyChanging();
			entity.Duty = this;
		}
		
		private void detach_Journeys(Journey entity)
		{
			this.SendPropertyChanging();
			entity.Duty = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Journey")]
	public partial class Journey : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Journey;
		
		private int _id_Duty;
		
		private int _id_Module;
		
		private string _str_RouteID;
		
		private System.Nullable<short> _int2_JourneyID;
		
		private System.Nullable<short> _int2_Direction;
		
		private System.Nullable<System.DateTime> _dat_JourneyStartDate;
		
		private System.Nullable<System.DateTime> _dat_JourneyStartTime;
		
		private System.Nullable<System.DateTime> _dat_JourneyStopDate;
		
		private System.Nullable<System.DateTime> _dat_JourneyStopTime;
		
		private System.Nullable<System.DateTime> _dat_TrafficDate;
		
		private System.Nullable<int> _int4_Distance;
		
		private System.Nullable<int> _int4_Traveled;
		
		private System.Nullable<int> _int4_JourneyRevenue;
		
		private System.Nullable<int> _int4_JourneyTickets;
		
		private System.Nullable<int> _int4_JourneyPasses;
		
		private System.Nullable<int> _int4_JourneyNonRevenue;
		
		private System.Nullable<int> _int4_JourneyTransfer;
		
		private System.Nullable<System.DateTime> _dat_RecordMod;
		
		private System.Nullable<int> _id_BatchNo;
		
		private System.Nullable<byte> _byt_IeType;
		
		private System.Nullable<System.DateTime> _dat_JourneyMoveTime;
		
		private System.Nullable<System.DateTime> _dat_JourneyArrivalTime;
		
		private System.Nullable<int> _int4_GPSDistance;
		
		private EntitySet<Stage> _Stages;
		
		private EntityRef<Duty> _Duty;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_JourneyChanging(int value);
    partial void Onid_JourneyChanged();
    partial void Onid_DutyChanging(int value);
    partial void Onid_DutyChanged();
    partial void Onid_ModuleChanging(int value);
    partial void Onid_ModuleChanged();
    partial void Onstr_RouteIDChanging(string value);
    partial void Onstr_RouteIDChanged();
    partial void Onint2_JourneyIDChanging(System.Nullable<short> value);
    partial void Onint2_JourneyIDChanged();
    partial void Onint2_DirectionChanging(System.Nullable<short> value);
    partial void Onint2_DirectionChanged();
    partial void Ondat_JourneyStartDateChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_JourneyStartDateChanged();
    partial void Ondat_JourneyStartTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_JourneyStartTimeChanged();
    partial void Ondat_JourneyStopDateChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_JourneyStopDateChanged();
    partial void Ondat_JourneyStopTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_JourneyStopTimeChanged();
    partial void Ondat_TrafficDateChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_TrafficDateChanged();
    partial void Onint4_DistanceChanging(System.Nullable<int> value);
    partial void Onint4_DistanceChanged();
    partial void Onint4_TraveledChanging(System.Nullable<int> value);
    partial void Onint4_TraveledChanged();
    partial void Onint4_JourneyRevenueChanging(System.Nullable<int> value);
    partial void Onint4_JourneyRevenueChanged();
    partial void Onint4_JourneyTicketsChanging(System.Nullable<int> value);
    partial void Onint4_JourneyTicketsChanged();
    partial void Onint4_JourneyPassesChanging(System.Nullable<int> value);
    partial void Onint4_JourneyPassesChanged();
    partial void Onint4_JourneyNonRevenueChanging(System.Nullable<int> value);
    partial void Onint4_JourneyNonRevenueChanged();
    partial void Onint4_JourneyTransferChanging(System.Nullable<int> value);
    partial void Onint4_JourneyTransferChanged();
    partial void Ondat_RecordModChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_RecordModChanged();
    partial void Onid_BatchNoChanging(System.Nullable<int> value);
    partial void Onid_BatchNoChanged();
    partial void Onbyt_IeTypeChanging(System.Nullable<byte> value);
    partial void Onbyt_IeTypeChanged();
    partial void Ondat_JourneyMoveTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_JourneyMoveTimeChanged();
    partial void Ondat_JourneyArrivalTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_JourneyArrivalTimeChanged();
    partial void Onint4_GPSDistanceChanging(System.Nullable<int> value);
    partial void Onint4_GPSDistanceChanged();
    #endregion
		
		public Journey()
		{
			this._Stages = new EntitySet<Stage>(new Action<Stage>(this.attach_Stages), new Action<Stage>(this.detach_Stages));
			this._Duty = default(EntityRef<Duty>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Journey", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_Journey
		{
			get
			{
				return this._id_Journey;
			}
			set
			{
				if ((this._id_Journey != value))
				{
					this.Onid_JourneyChanging(value);
					this.SendPropertyChanging();
					this._id_Journey = value;
					this.SendPropertyChanged("id_Journey");
					this.Onid_JourneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Duty", DbType="Int NOT NULL")]
		public int id_Duty
		{
			get
			{
				return this._id_Duty;
			}
			set
			{
				if ((this._id_Duty != value))
				{
					if (this._Duty.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_DutyChanging(value);
					this.SendPropertyChanging();
					this._id_Duty = value;
					this.SendPropertyChanged("id_Duty");
					this.Onid_DutyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Module", DbType="Int NOT NULL")]
		public int id_Module
		{
			get
			{
				return this._id_Module;
			}
			set
			{
				if ((this._id_Module != value))
				{
					this.Onid_ModuleChanging(value);
					this.SendPropertyChanging();
					this._id_Module = value;
					this.SendPropertyChanged("id_Module");
					this.Onid_ModuleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_str_RouteID", DbType="Char(4)")]
		public string str_RouteID
		{
			get
			{
				return this._str_RouteID;
			}
			set
			{
				if ((this._str_RouteID != value))
				{
					this.Onstr_RouteIDChanging(value);
					this.SendPropertyChanging();
					this._str_RouteID = value;
					this.SendPropertyChanged("str_RouteID");
					this.Onstr_RouteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int2_JourneyID", DbType="SmallInt")]
		public System.Nullable<short> int2_JourneyID
		{
			get
			{
				return this._int2_JourneyID;
			}
			set
			{
				if ((this._int2_JourneyID != value))
				{
					this.Onint2_JourneyIDChanging(value);
					this.SendPropertyChanging();
					this._int2_JourneyID = value;
					this.SendPropertyChanged("int2_JourneyID");
					this.Onint2_JourneyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int2_Direction", DbType="SmallInt")]
		public System.Nullable<short> int2_Direction
		{
			get
			{
				return this._int2_Direction;
			}
			set
			{
				if ((this._int2_Direction != value))
				{
					this.Onint2_DirectionChanging(value);
					this.SendPropertyChanging();
					this._int2_Direction = value;
					this.SendPropertyChanged("int2_Direction");
					this.Onint2_DirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_JourneyStartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_JourneyStartDate
		{
			get
			{
				return this._dat_JourneyStartDate;
			}
			set
			{
				if ((this._dat_JourneyStartDate != value))
				{
					this.Ondat_JourneyStartDateChanging(value);
					this.SendPropertyChanging();
					this._dat_JourneyStartDate = value;
					this.SendPropertyChanged("dat_JourneyStartDate");
					this.Ondat_JourneyStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_JourneyStartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_JourneyStartTime
		{
			get
			{
				return this._dat_JourneyStartTime;
			}
			set
			{
				if ((this._dat_JourneyStartTime != value))
				{
					this.Ondat_JourneyStartTimeChanging(value);
					this.SendPropertyChanging();
					this._dat_JourneyStartTime = value;
					this.SendPropertyChanged("dat_JourneyStartTime");
					this.Ondat_JourneyStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_JourneyStopDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_JourneyStopDate
		{
			get
			{
				return this._dat_JourneyStopDate;
			}
			set
			{
				if ((this._dat_JourneyStopDate != value))
				{
					this.Ondat_JourneyStopDateChanging(value);
					this.SendPropertyChanging();
					this._dat_JourneyStopDate = value;
					this.SendPropertyChanged("dat_JourneyStopDate");
					this.Ondat_JourneyStopDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_JourneyStopTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_JourneyStopTime
		{
			get
			{
				return this._dat_JourneyStopTime;
			}
			set
			{
				if ((this._dat_JourneyStopTime != value))
				{
					this.Ondat_JourneyStopTimeChanging(value);
					this.SendPropertyChanging();
					this._dat_JourneyStopTime = value;
					this.SendPropertyChanged("dat_JourneyStopTime");
					this.Ondat_JourneyStopTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_TrafficDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_TrafficDate
		{
			get
			{
				return this._dat_TrafficDate;
			}
			set
			{
				if ((this._dat_TrafficDate != value))
				{
					this.Ondat_TrafficDateChanging(value);
					this.SendPropertyChanging();
					this._dat_TrafficDate = value;
					this.SendPropertyChanged("dat_TrafficDate");
					this.Ondat_TrafficDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_Distance", DbType="Int")]
		public System.Nullable<int> int4_Distance
		{
			get
			{
				return this._int4_Distance;
			}
			set
			{
				if ((this._int4_Distance != value))
				{
					this.Onint4_DistanceChanging(value);
					this.SendPropertyChanging();
					this._int4_Distance = value;
					this.SendPropertyChanged("int4_Distance");
					this.Onint4_DistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_Traveled", DbType="Int")]
		public System.Nullable<int> int4_Traveled
		{
			get
			{
				return this._int4_Traveled;
			}
			set
			{
				if ((this._int4_Traveled != value))
				{
					this.Onint4_TraveledChanging(value);
					this.SendPropertyChanging();
					this._int4_Traveled = value;
					this.SendPropertyChanged("int4_Traveled");
					this.Onint4_TraveledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_JourneyRevenue", DbType="Int")]
		public System.Nullable<int> int4_JourneyRevenue
		{
			get
			{
				return this._int4_JourneyRevenue;
			}
			set
			{
				if ((this._int4_JourneyRevenue != value))
				{
					this.Onint4_JourneyRevenueChanging(value);
					this.SendPropertyChanging();
					this._int4_JourneyRevenue = value;
					this.SendPropertyChanged("int4_JourneyRevenue");
					this.Onint4_JourneyRevenueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_JourneyTickets", DbType="Int")]
		public System.Nullable<int> int4_JourneyTickets
		{
			get
			{
				return this._int4_JourneyTickets;
			}
			set
			{
				if ((this._int4_JourneyTickets != value))
				{
					this.Onint4_JourneyTicketsChanging(value);
					this.SendPropertyChanging();
					this._int4_JourneyTickets = value;
					this.SendPropertyChanged("int4_JourneyTickets");
					this.Onint4_JourneyTicketsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_JourneyPasses", DbType="Int")]
		public System.Nullable<int> int4_JourneyPasses
		{
			get
			{
				return this._int4_JourneyPasses;
			}
			set
			{
				if ((this._int4_JourneyPasses != value))
				{
					this.Onint4_JourneyPassesChanging(value);
					this.SendPropertyChanging();
					this._int4_JourneyPasses = value;
					this.SendPropertyChanged("int4_JourneyPasses");
					this.Onint4_JourneyPassesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_JourneyNonRevenue", DbType="Int")]
		public System.Nullable<int> int4_JourneyNonRevenue
		{
			get
			{
				return this._int4_JourneyNonRevenue;
			}
			set
			{
				if ((this._int4_JourneyNonRevenue != value))
				{
					this.Onint4_JourneyNonRevenueChanging(value);
					this.SendPropertyChanging();
					this._int4_JourneyNonRevenue = value;
					this.SendPropertyChanged("int4_JourneyNonRevenue");
					this.Onint4_JourneyNonRevenueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_JourneyTransfer", DbType="Int")]
		public System.Nullable<int> int4_JourneyTransfer
		{
			get
			{
				return this._int4_JourneyTransfer;
			}
			set
			{
				if ((this._int4_JourneyTransfer != value))
				{
					this.Onint4_JourneyTransferChanging(value);
					this.SendPropertyChanging();
					this._int4_JourneyTransfer = value;
					this.SendPropertyChanged("int4_JourneyTransfer");
					this.Onint4_JourneyTransferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_RecordMod", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_RecordMod
		{
			get
			{
				return this._dat_RecordMod;
			}
			set
			{
				if ((this._dat_RecordMod != value))
				{
					this.Ondat_RecordModChanging(value);
					this.SendPropertyChanging();
					this._dat_RecordMod = value;
					this.SendPropertyChanged("dat_RecordMod");
					this.Ondat_RecordModChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_BatchNo", DbType="Int")]
		public System.Nullable<int> id_BatchNo
		{
			get
			{
				return this._id_BatchNo;
			}
			set
			{
				if ((this._id_BatchNo != value))
				{
					this.Onid_BatchNoChanging(value);
					this.SendPropertyChanging();
					this._id_BatchNo = value;
					this.SendPropertyChanged("id_BatchNo");
					this.Onid_BatchNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_byt_IeType", DbType="TinyInt")]
		public System.Nullable<byte> byt_IeType
		{
			get
			{
				return this._byt_IeType;
			}
			set
			{
				if ((this._byt_IeType != value))
				{
					this.Onbyt_IeTypeChanging(value);
					this.SendPropertyChanging();
					this._byt_IeType = value;
					this.SendPropertyChanged("byt_IeType");
					this.Onbyt_IeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_JourneyMoveTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_JourneyMoveTime
		{
			get
			{
				return this._dat_JourneyMoveTime;
			}
			set
			{
				if ((this._dat_JourneyMoveTime != value))
				{
					this.Ondat_JourneyMoveTimeChanging(value);
					this.SendPropertyChanging();
					this._dat_JourneyMoveTime = value;
					this.SendPropertyChanged("dat_JourneyMoveTime");
					this.Ondat_JourneyMoveTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_JourneyArrivalTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_JourneyArrivalTime
		{
			get
			{
				return this._dat_JourneyArrivalTime;
			}
			set
			{
				if ((this._dat_JourneyArrivalTime != value))
				{
					this.Ondat_JourneyArrivalTimeChanging(value);
					this.SendPropertyChanging();
					this._dat_JourneyArrivalTime = value;
					this.SendPropertyChanged("dat_JourneyArrivalTime");
					this.Ondat_JourneyArrivalTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_GPSDistance", DbType="Int")]
		public System.Nullable<int> int4_GPSDistance
		{
			get
			{
				return this._int4_GPSDistance;
			}
			set
			{
				if ((this._int4_GPSDistance != value))
				{
					this.Onint4_GPSDistanceChanging(value);
					this.SendPropertyChanging();
					this._int4_GPSDistance = value;
					this.SendPropertyChanged("int4_GPSDistance");
					this.Onint4_GPSDistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Journey_Stage", Storage="_Stages", ThisKey="id_Journey", OtherKey="id_Journey")]
		public EntitySet<Stage> Stages
		{
			get
			{
				return this._Stages;
			}
			set
			{
				this._Stages.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Duty_Journey", Storage="_Duty", ThisKey="id_Duty", OtherKey="id_Duty", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Duty Duty
		{
			get
			{
				return this._Duty.Entity;
			}
			set
			{
				Duty previousValue = this._Duty.Entity;
				if (((previousValue != value) 
							|| (this._Duty.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Duty.Entity = null;
						previousValue.Journeys.Remove(this);
					}
					this._Duty.Entity = value;
					if ((value != null))
					{
						value.Journeys.Add(this);
						this._id_Duty = value.id_Duty;
					}
					else
					{
						this._id_Duty = default(int);
					}
					this.SendPropertyChanged("Duty");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Stages(Stage entity)
		{
			this.SendPropertyChanging();
			entity.Journey = this;
		}
		
		private void detach_Stages(Stage entity)
		{
			this.SendPropertyChanging();
			entity.Journey = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Stage")]
	public partial class Stage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Stage;
		
		private int _id_Journey;
		
		private int _id_Duty;
		
		private int _id_Module;
		
		private System.Nullable<short> _int2_StageID;
		
		private System.Nullable<System.DateTime> _dat_StageDate;
		
		private System.Nullable<System.DateTime> _dat_StageTime;
		
		private System.Nullable<System.DateTime> _dat_RecordMod;
		
		private System.Nullable<int> _id_BatchNo;
		
		private EntitySet<Tran> _Trans;
		
		private EntityRef<Journey> _Journey;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_StageChanging(int value);
    partial void Onid_StageChanged();
    partial void Onid_JourneyChanging(int value);
    partial void Onid_JourneyChanged();
    partial void Onid_DutyChanging(int value);
    partial void Onid_DutyChanged();
    partial void Onid_ModuleChanging(int value);
    partial void Onid_ModuleChanged();
    partial void Onint2_StageIDChanging(System.Nullable<short> value);
    partial void Onint2_StageIDChanged();
    partial void Ondat_StageDateChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_StageDateChanged();
    partial void Ondat_StageTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_StageTimeChanged();
    partial void Ondat_RecordModChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_RecordModChanged();
    partial void Onid_BatchNoChanging(System.Nullable<int> value);
    partial void Onid_BatchNoChanged();
    #endregion
		
		public Stage()
		{
			this._Trans = new EntitySet<Tran>(new Action<Tran>(this.attach_Trans), new Action<Tran>(this.detach_Trans));
			this._Journey = default(EntityRef<Journey>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Stage", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_Stage
		{
			get
			{
				return this._id_Stage;
			}
			set
			{
				if ((this._id_Stage != value))
				{
					this.Onid_StageChanging(value);
					this.SendPropertyChanging();
					this._id_Stage = value;
					this.SendPropertyChanged("id_Stage");
					this.Onid_StageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Journey", DbType="Int NOT NULL")]
		public int id_Journey
		{
			get
			{
				return this._id_Journey;
			}
			set
			{
				if ((this._id_Journey != value))
				{
					if (this._Journey.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_JourneyChanging(value);
					this.SendPropertyChanging();
					this._id_Journey = value;
					this.SendPropertyChanged("id_Journey");
					this.Onid_JourneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Duty", DbType="Int NOT NULL")]
		public int id_Duty
		{
			get
			{
				return this._id_Duty;
			}
			set
			{
				if ((this._id_Duty != value))
				{
					this.Onid_DutyChanging(value);
					this.SendPropertyChanging();
					this._id_Duty = value;
					this.SendPropertyChanged("id_Duty");
					this.Onid_DutyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Module", DbType="Int NOT NULL")]
		public int id_Module
		{
			get
			{
				return this._id_Module;
			}
			set
			{
				if ((this._id_Module != value))
				{
					this.Onid_ModuleChanging(value);
					this.SendPropertyChanging();
					this._id_Module = value;
					this.SendPropertyChanged("id_Module");
					this.Onid_ModuleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int2_StageID", DbType="SmallInt")]
		public System.Nullable<short> int2_StageID
		{
			get
			{
				return this._int2_StageID;
			}
			set
			{
				if ((this._int2_StageID != value))
				{
					this.Onint2_StageIDChanging(value);
					this.SendPropertyChanging();
					this._int2_StageID = value;
					this.SendPropertyChanged("int2_StageID");
					this.Onint2_StageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_StageDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_StageDate
		{
			get
			{
				return this._dat_StageDate;
			}
			set
			{
				if ((this._dat_StageDate != value))
				{
					this.Ondat_StageDateChanging(value);
					this.SendPropertyChanging();
					this._dat_StageDate = value;
					this.SendPropertyChanged("dat_StageDate");
					this.Ondat_StageDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_StageTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_StageTime
		{
			get
			{
				return this._dat_StageTime;
			}
			set
			{
				if ((this._dat_StageTime != value))
				{
					this.Ondat_StageTimeChanging(value);
					this.SendPropertyChanging();
					this._dat_StageTime = value;
					this.SendPropertyChanged("dat_StageTime");
					this.Ondat_StageTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_RecordMod", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_RecordMod
		{
			get
			{
				return this._dat_RecordMod;
			}
			set
			{
				if ((this._dat_RecordMod != value))
				{
					this.Ondat_RecordModChanging(value);
					this.SendPropertyChanging();
					this._dat_RecordMod = value;
					this.SendPropertyChanged("dat_RecordMod");
					this.Ondat_RecordModChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_BatchNo", DbType="Int")]
		public System.Nullable<int> id_BatchNo
		{
			get
			{
				return this._id_BatchNo;
			}
			set
			{
				if ((this._id_BatchNo != value))
				{
					this.Onid_BatchNoChanging(value);
					this.SendPropertyChanging();
					this._id_BatchNo = value;
					this.SendPropertyChanged("id_BatchNo");
					this.Onid_BatchNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Stage_Tran", Storage="_Trans", ThisKey="id_Stage", OtherKey="id_Stage")]
		public EntitySet<Tran> Trans
		{
			get
			{
				return this._Trans;
			}
			set
			{
				this._Trans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Journey_Stage", Storage="_Journey", ThisKey="id_Journey", OtherKey="id_Journey", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Journey Journey
		{
			get
			{
				return this._Journey.Entity;
			}
			set
			{
				Journey previousValue = this._Journey.Entity;
				if (((previousValue != value) 
							|| (this._Journey.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Journey.Entity = null;
						previousValue.Stages.Remove(this);
					}
					this._Journey.Entity = value;
					if ((value != null))
					{
						value.Stages.Add(this);
						this._id_Journey = value.id_Journey;
					}
					else
					{
						this._id_Journey = default(int);
					}
					this.SendPropertyChanged("Journey");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Trans(Tran entity)
		{
			this.SendPropertyChanging();
			entity.Stage = this;
		}
		
		private void detach_Trans(Tran entity)
		{
			this.SendPropertyChanging();
			entity.Stage = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Trans")]
	public partial class Tran : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Trans;
		
		private int _id_Stage;
		
		private int _id_Journey;
		
		private int _id_Duty;
		
		private int _id_Module;
		
		private string _str_LocationCode;
		
		private System.Nullable<short> _int2_BoardingStageID;
		
		private System.Nullable<short> _int2_AlightingStageID;
		
		private System.Nullable<short> _int2_Class;
		
		private System.Nullable<int> _int4_Revenue;
		
		private System.Nullable<int> _int4_NonRevenue;
		
		private System.Nullable<short> _int2_TicketCount;
		
		private System.Nullable<short> _int2_PassCount;
		
		private System.Nullable<short> _int2_Transfers;
		
		private System.Nullable<System.DateTime> _dat_TransDate;
		
		private System.Nullable<System.DateTime> _dat_TransTime;
		
		private string _str_SerialNumber;
		
		private System.Nullable<int> _int4_RevenueBal;
		
		private System.Nullable<int> _int4_TripBal;
		
		private System.Nullable<int> _int2_AnnulCount;
		
		private System.Nullable<int> _int4_AnnulCash;
		
		private EntityRef<Stage> _Stage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_TransChanging(int value);
    partial void Onid_TransChanged();
    partial void Onid_StageChanging(int value);
    partial void Onid_StageChanged();
    partial void Onid_JourneyChanging(int value);
    partial void Onid_JourneyChanged();
    partial void Onid_DutyChanging(int value);
    partial void Onid_DutyChanged();
    partial void Onid_ModuleChanging(int value);
    partial void Onid_ModuleChanged();
    partial void Onstr_LocationCodeChanging(string value);
    partial void Onstr_LocationCodeChanged();
    partial void Onint2_BoardingStageIDChanging(System.Nullable<short> value);
    partial void Onint2_BoardingStageIDChanged();
    partial void Onint2_AlightingStageIDChanging(System.Nullable<short> value);
    partial void Onint2_AlightingStageIDChanged();
    partial void Onint2_ClassChanging(System.Nullable<short> value);
    partial void Onint2_ClassChanged();
    partial void Onint4_RevenueChanging(System.Nullable<int> value);
    partial void Onint4_RevenueChanged();
    partial void Onint4_NonRevenueChanging(System.Nullable<int> value);
    partial void Onint4_NonRevenueChanged();
    partial void Onint2_TicketCountChanging(System.Nullable<short> value);
    partial void Onint2_TicketCountChanged();
    partial void Onint2_PassCountChanging(System.Nullable<short> value);
    partial void Onint2_PassCountChanged();
    partial void Onint2_TransfersChanging(System.Nullable<short> value);
    partial void Onint2_TransfersChanged();
    partial void Ondat_TransDateChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_TransDateChanged();
    partial void Ondat_TransTimeChanging(System.Nullable<System.DateTime> value);
    partial void Ondat_TransTimeChanged();
    partial void Onstr_SerialNumberChanging(string value);
    partial void Onstr_SerialNumberChanged();
    partial void Onint4_RevenueBalChanging(System.Nullable<int> value);
    partial void Onint4_RevenueBalChanged();
    partial void Onint4_TripBalChanging(System.Nullable<int> value);
    partial void Onint4_TripBalChanged();
    partial void Onint2_AnnulCountChanging(System.Nullable<int> value);
    partial void Onint2_AnnulCountChanged();
    partial void Onint4_AnnulCashChanging(System.Nullable<int> value);
    partial void Onint4_AnnulCashChanged();
    #endregion
		
		public Tran()
		{
			this._Stage = default(EntityRef<Stage>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Trans", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_Trans
		{
			get
			{
				return this._id_Trans;
			}
			set
			{
				if ((this._id_Trans != value))
				{
					this.Onid_TransChanging(value);
					this.SendPropertyChanging();
					this._id_Trans = value;
					this.SendPropertyChanged("id_Trans");
					this.Onid_TransChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Stage", DbType="Int NOT NULL")]
		public int id_Stage
		{
			get
			{
				return this._id_Stage;
			}
			set
			{
				if ((this._id_Stage != value))
				{
					if (this._Stage.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_StageChanging(value);
					this.SendPropertyChanging();
					this._id_Stage = value;
					this.SendPropertyChanged("id_Stage");
					this.Onid_StageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Journey", DbType="Int NOT NULL")]
		public int id_Journey
		{
			get
			{
				return this._id_Journey;
			}
			set
			{
				if ((this._id_Journey != value))
				{
					this.Onid_JourneyChanging(value);
					this.SendPropertyChanging();
					this._id_Journey = value;
					this.SendPropertyChanged("id_Journey");
					this.Onid_JourneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Duty", DbType="Int NOT NULL")]
		public int id_Duty
		{
			get
			{
				return this._id_Duty;
			}
			set
			{
				if ((this._id_Duty != value))
				{
					this.Onid_DutyChanging(value);
					this.SendPropertyChanging();
					this._id_Duty = value;
					this.SendPropertyChanged("id_Duty");
					this.Onid_DutyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Module", DbType="Int NOT NULL")]
		public int id_Module
		{
			get
			{
				return this._id_Module;
			}
			set
			{
				if ((this._id_Module != value))
				{
					this.Onid_ModuleChanging(value);
					this.SendPropertyChanging();
					this._id_Module = value;
					this.SendPropertyChanged("id_Module");
					this.Onid_ModuleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_str_LocationCode", DbType="Char(2)")]
		public string str_LocationCode
		{
			get
			{
				return this._str_LocationCode;
			}
			set
			{
				if ((this._str_LocationCode != value))
				{
					this.Onstr_LocationCodeChanging(value);
					this.SendPropertyChanging();
					this._str_LocationCode = value;
					this.SendPropertyChanged("str_LocationCode");
					this.Onstr_LocationCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int2_BoardingStageID", DbType="SmallInt")]
		public System.Nullable<short> int2_BoardingStageID
		{
			get
			{
				return this._int2_BoardingStageID;
			}
			set
			{
				if ((this._int2_BoardingStageID != value))
				{
					this.Onint2_BoardingStageIDChanging(value);
					this.SendPropertyChanging();
					this._int2_BoardingStageID = value;
					this.SendPropertyChanged("int2_BoardingStageID");
					this.Onint2_BoardingStageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int2_AlightingStageID", DbType="SmallInt")]
		public System.Nullable<short> int2_AlightingStageID
		{
			get
			{
				return this._int2_AlightingStageID;
			}
			set
			{
				if ((this._int2_AlightingStageID != value))
				{
					this.Onint2_AlightingStageIDChanging(value);
					this.SendPropertyChanging();
					this._int2_AlightingStageID = value;
					this.SendPropertyChanged("int2_AlightingStageID");
					this.Onint2_AlightingStageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int2_Class", DbType="SmallInt")]
		public System.Nullable<short> int2_Class
		{
			get
			{
				return this._int2_Class;
			}
			set
			{
				if ((this._int2_Class != value))
				{
					this.Onint2_ClassChanging(value);
					this.SendPropertyChanging();
					this._int2_Class = value;
					this.SendPropertyChanged("int2_Class");
					this.Onint2_ClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_Revenue", DbType="Int")]
		public System.Nullable<int> int4_Revenue
		{
			get
			{
				return this._int4_Revenue;
			}
			set
			{
				if ((this._int4_Revenue != value))
				{
					this.Onint4_RevenueChanging(value);
					this.SendPropertyChanging();
					this._int4_Revenue = value;
					this.SendPropertyChanged("int4_Revenue");
					this.Onint4_RevenueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_NonRevenue", DbType="Int")]
		public System.Nullable<int> int4_NonRevenue
		{
			get
			{
				return this._int4_NonRevenue;
			}
			set
			{
				if ((this._int4_NonRevenue != value))
				{
					this.Onint4_NonRevenueChanging(value);
					this.SendPropertyChanging();
					this._int4_NonRevenue = value;
					this.SendPropertyChanged("int4_NonRevenue");
					this.Onint4_NonRevenueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int2_TicketCount", DbType="SmallInt")]
		public System.Nullable<short> int2_TicketCount
		{
			get
			{
				return this._int2_TicketCount;
			}
			set
			{
				if ((this._int2_TicketCount != value))
				{
					this.Onint2_TicketCountChanging(value);
					this.SendPropertyChanging();
					this._int2_TicketCount = value;
					this.SendPropertyChanged("int2_TicketCount");
					this.Onint2_TicketCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int2_PassCount", DbType="SmallInt")]
		public System.Nullable<short> int2_PassCount
		{
			get
			{
				return this._int2_PassCount;
			}
			set
			{
				if ((this._int2_PassCount != value))
				{
					this.Onint2_PassCountChanging(value);
					this.SendPropertyChanging();
					this._int2_PassCount = value;
					this.SendPropertyChanged("int2_PassCount");
					this.Onint2_PassCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int2_Transfers", DbType="SmallInt")]
		public System.Nullable<short> int2_Transfers
		{
			get
			{
				return this._int2_Transfers;
			}
			set
			{
				if ((this._int2_Transfers != value))
				{
					this.Onint2_TransfersChanging(value);
					this.SendPropertyChanging();
					this._int2_Transfers = value;
					this.SendPropertyChanged("int2_Transfers");
					this.Onint2_TransfersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_TransDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_TransDate
		{
			get
			{
				return this._dat_TransDate;
			}
			set
			{
				if ((this._dat_TransDate != value))
				{
					this.Ondat_TransDateChanging(value);
					this.SendPropertyChanging();
					this._dat_TransDate = value;
					this.SendPropertyChanged("dat_TransDate");
					this.Ondat_TransDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_TransTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_TransTime
		{
			get
			{
				return this._dat_TransTime;
			}
			set
			{
				if ((this._dat_TransTime != value))
				{
					this.Ondat_TransTimeChanging(value);
					this.SendPropertyChanging();
					this._dat_TransTime = value;
					this.SendPropertyChanged("dat_TransTime");
					this.Ondat_TransTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_str_SerialNumber", DbType="VarChar(10)")]
		public string str_SerialNumber
		{
			get
			{
				return this._str_SerialNumber;
			}
			set
			{
				if ((this._str_SerialNumber != value))
				{
					this.Onstr_SerialNumberChanging(value);
					this.SendPropertyChanging();
					this._str_SerialNumber = value;
					this.SendPropertyChanged("str_SerialNumber");
					this.Onstr_SerialNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_RevenueBal", DbType="Int")]
		public System.Nullable<int> int4_RevenueBal
		{
			get
			{
				return this._int4_RevenueBal;
			}
			set
			{
				if ((this._int4_RevenueBal != value))
				{
					this.Onint4_RevenueBalChanging(value);
					this.SendPropertyChanging();
					this._int4_RevenueBal = value;
					this.SendPropertyChanged("int4_RevenueBal");
					this.Onint4_RevenueBalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_TripBal", DbType="Int")]
		public System.Nullable<int> int4_TripBal
		{
			get
			{
				return this._int4_TripBal;
			}
			set
			{
				if ((this._int4_TripBal != value))
				{
					this.Onint4_TripBalChanging(value);
					this.SendPropertyChanging();
					this._int4_TripBal = value;
					this.SendPropertyChanged("int4_TripBal");
					this.Onint4_TripBalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int2_AnnulCount", DbType="Int")]
		public System.Nullable<int> int2_AnnulCount
		{
			get
			{
				return this._int2_AnnulCount;
			}
			set
			{
				if ((this._int2_AnnulCount != value))
				{
					this.Onint2_AnnulCountChanging(value);
					this.SendPropertyChanging();
					this._int2_AnnulCount = value;
					this.SendPropertyChanged("int2_AnnulCount");
					this.Onint2_AnnulCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_AnnulCash", DbType="Int")]
		public System.Nullable<int> int4_AnnulCash
		{
			get
			{
				return this._int4_AnnulCash;
			}
			set
			{
				if ((this._int4_AnnulCash != value))
				{
					this.Onint4_AnnulCashChanging(value);
					this.SendPropertyChanging();
					this._int4_AnnulCash = value;
					this.SendPropertyChanged("int4_AnnulCash");
					this.Onint4_AnnulCashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Stage_Tran", Storage="_Stage", ThisKey="id_Stage", OtherKey="id_Stage", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Stage Stage
		{
			get
			{
				return this._Stage.Entity;
			}
			set
			{
				Stage previousValue = this._Stage.Entity;
				if (((previousValue != value) 
							|| (this._Stage.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Stage.Entity = null;
						previousValue.Trans.Remove(this);
					}
					this._Stage.Entity = value;
					if ((value != null))
					{
						value.Trans.Add(this);
						this._id_Stage = value.id_Stage;
					}
					else
					{
						this._id_Stage = default(int);
					}
					this.SendPropertyChanged("Stage");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Waybill")]
	public partial class Waybill
	{
		
		private int _ModuleID;
		
		private System.Nullable<System.DateTime> _dat_Start;
		
		private System.Nullable<System.DateTime> _dat_End;
		
		private System.Nullable<int> _int4_Operator;
		
		private string _str8_BusID;
		
		private string _str6_EtmID;
		
		private System.Nullable<int> _int4_EtmGrandTotal;
		
		private System.Nullable<int> _int4_Revenue;
		
		private System.Nullable<System.DateTime> _dat_Match;
		
		private System.Nullable<System.DateTime> _dat_Actual;
		
		private System.Nullable<int> _Imported_Operator;
		
		private string _Imported_BusID;
		
		private string _Imported_ETMID;
		
		private System.Nullable<int> _Imported_GT;
		
		private System.Nullable<int> _Imported_Revenue;
		
		public Waybill()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleID", DbType="Int NOT NULL")]
		public int ModuleID
		{
			get
			{
				return this._ModuleID;
			}
			set
			{
				if ((this._ModuleID != value))
				{
					this._ModuleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_Start", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_Start
		{
			get
			{
				return this._dat_Start;
			}
			set
			{
				if ((this._dat_Start != value))
				{
					this._dat_Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_End", DbType="DateTime")]
		public System.Nullable<System.DateTime> dat_End
		{
			get
			{
				return this._dat_End;
			}
			set
			{
				if ((this._dat_End != value))
				{
					this._dat_End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_Operator", DbType="Int")]
		public System.Nullable<int> int4_Operator
		{
			get
			{
				return this._int4_Operator;
			}
			set
			{
				if ((this._int4_Operator != value))
				{
					this._int4_Operator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_str8_BusID", DbType="VarChar(8)")]
		public string str8_BusID
		{
			get
			{
				return this._str8_BusID;
			}
			set
			{
				if ((this._str8_BusID != value))
				{
					this._str8_BusID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_str6_EtmID", DbType="VarChar(6)")]
		public string str6_EtmID
		{
			get
			{
				return this._str6_EtmID;
			}
			set
			{
				if ((this._str6_EtmID != value))
				{
					this._str6_EtmID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_EtmGrandTotal", DbType="Int")]
		public System.Nullable<int> int4_EtmGrandTotal
		{
			get
			{
				return this._int4_EtmGrandTotal;
			}
			set
			{
				if ((this._int4_EtmGrandTotal != value))
				{
					this._int4_EtmGrandTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int4_Revenue", DbType="Int")]
		public System.Nullable<int> int4_Revenue
		{
			get
			{
				return this._int4_Revenue;
			}
			set
			{
				if ((this._int4_Revenue != value))
				{
					this._int4_Revenue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_Match", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> dat_Match
		{
			get
			{
				return this._dat_Match;
			}
			set
			{
				if ((this._dat_Match != value))
				{
					this._dat_Match = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_Actual", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> dat_Actual
		{
			get
			{
				return this._dat_Actual;
			}
			set
			{
				if ((this._dat_Actual != value))
				{
					this._dat_Actual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imported_Operator", DbType="Int")]
		public System.Nullable<int> Imported_Operator
		{
			get
			{
				return this._Imported_Operator;
			}
			set
			{
				if ((this._Imported_Operator != value))
				{
					this._Imported_Operator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imported_BusID", DbType="VarChar(8)")]
		public string Imported_BusID
		{
			get
			{
				return this._Imported_BusID;
			}
			set
			{
				if ((this._Imported_BusID != value))
				{
					this._Imported_BusID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imported_ETMID", DbType="VarChar(6)")]
		public string Imported_ETMID
		{
			get
			{
				return this._Imported_ETMID;
			}
			set
			{
				if ((this._Imported_ETMID != value))
				{
					this._Imported_ETMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imported_GT", DbType="Int")]
		public System.Nullable<int> Imported_GT
		{
			get
			{
				return this._Imported_GT;
			}
			set
			{
				if ((this._Imported_GT != value))
				{
					this._Imported_GT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imported_Revenue", DbType="Int")]
		public System.Nullable<int> Imported_Revenue
		{
			get
			{
				return this._Imported_Revenue;
			}
			set
			{
				if ((this._Imported_Revenue != value))
				{
					this._Imported_Revenue = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
